create table transferencia (
    id bigint generated by default as identity (start with 1) not null primary key,
    conta_origem text,
    conta_destino text,
    valor_trans numeric,
    taxa numeric,
    data_trans date,
    data_agend date
);